const data = {
    products: [
      {
        name: 'Head-set1',
        slug: 'head-set1',
        category: 'digitals',
        image: '/assets/images/products/product1.png',
        price: 70,
        brand: 'a4tech',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'This is a very nice headset',
      },
      {
        name: 'Head-set2',
        slug: 'head-set2',
        category: 'digitals',
        image: '/assets/images/products/product2.png',
        price: 80,
        brand: 'sony',
        rating: 4.2,
        numReviews: 10,
        countInStock: 20,
        description: 'This is a very nice joystick',
      },
      {
        name: 'Head-set3',
        slug: 'head-set3',
        category: 'digitals',
        image: '/assets/images/products/product3.jpg',
        price: 840,
        brand: 'sony',
        rating: 3.2,
        numReviews: 100,
        countInStock: 240,
        description: 'This is a very nice headset',
      },
      {
        name: 'Head-set4',
        slug: 'head-set4',
        category: 'digitals',
        image: '/assets/images/products/product4.jpg',
        price: 810,
        brand: 'sony',
        rating: 2.2,
        numReviews: 110,
        countInStock: 210,
        description: 'This is a very nice mobile',
      },
      {
        name: 'Head-set5',
        slug: 'head-set5',
        category: 'digitals',
        image: '/assets/images/products/product5.webp',
        price: 850,
        brand: 'a4tech',
        rating: 9.2,
        numReviews: 150,
        countInStock: 250,
        description: 'This is a very nice charger',
      },
      {
        name: 'Head-set6',
        slug: 'head-set6',
        category: 'digitals',
        image: '/assets/images/products/product6.jpg',
        price: 8000,
        brand: 'sony',
        rating: 4.2,
        numReviews: 10,
        countInStock: 20,
        description: 'This is a very nice headset',
      },
     
    ],
  };
  export default data;